# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:blue)\
$docker_context\
$kubernetes\
[](fg:blue bg:purple)\
$time\
[ ](fg:purple)\
$line_break$character"""

palette = 'catppuccin_mocha'


[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[os]
disabled = false
style = 'bg:surface0 fg:text'

[os.symbols]
Alpaquita = ''
Alpine = ''
AlmaLinux = ''
Amazon = ''
Android = ''
Arch = ''
Artix = ''
CachyOS = ''
CentOS = ''
Debian = ''
DragonFly = ''
Emscripten = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = '󰛓'
Gentoo = ''
HardenedBSD = '󰞌'
Illumos = '󰈸'
Kali = ''
Linux = ''
Mabox = ''
Macos = ''
Manjaro = ''
Mariner = ''
MidnightBSD = ''
Mint = ''
NetBSD = ''
NixOS = ''
Nobara = ''
OpenBSD = '󰈺'
openSUSE = ''
OracleLinux = '󰌷'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Redox = '󰀘'
Solus = '󰠳'
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'

[username]
show_always = true
style_user = 'bg:surface0 fg:text'
style_root = 'bg:surface0 fg:text'
format = '[ $user ]($style)'

[directory]
style = 'fg:mantle bg:peach'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = '󰌾'

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ''
'Music' = '󰝚'
'Pictures' = ''
'Developer' = '󰲋'

[git_branch]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = 'bg:teal'
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = ' '
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ''
style = 'bg:teal'
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ''
style = 'bg:mantle'
format = '[[ $symbol( $context) ](fg:mantle bg:blue)]($style)'

[kubernetes]
symbol = "☸"
disabled = true
style = 'bg:mantle'
format = '[[ $symbol( $context) ](fg:mantle bg:blue)]($style)'
detect_files = ['Chart.yaml', '.helmignore', 'values.yaml', 'Chart.lock']
detect_folders = []

[time]
disabled = false
time_format = '%R'
format = '[  $time ](fg:mantle bg:purple)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
